name: kubectl-tap
on:
  push:
    # trigger on push to master
    branches: [master]
    # and on semver tag
    tags:
      - v*.*.*

jobs:
  build:
    timeout-minutes: 15
    name: Go build kubectl-tap
    runs-on: ubuntu-latest
    steps:
    - 
      name: Setup Go env
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.2'
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - 
      name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl
        sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo “deb https://apt.kubernetes.io/ kubernetes-xenial main” | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y zsh kubectl 
    - 
      name: Lint and Test
      run: |
        go generate ./...
    - 
      name: Build
      run: |
        go install -v -trimpath -ldflags="-s -w" ./cmd/kubectl-tap
    - 
      name: Integration Test
      run: ./scripts/ig-test.zsh

  docker-build-scratch:
    timeout-minutes: 10
    name: gcr.io/soluble-oss/kubectl-tap:latest
    needs: build
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Build binary and push to GCR
      uses: docker/build-push-action@v1
      with:
        path: .
        dockerfile: Dockerfile
        username: _json_key
        password: ${{ secrets.SOLUBLE_GCR_OSS_JSON }}
        registry: gcr.io
        repository: soluble-oss/kubectl-tap
        tags: latest

  docker-build-alpine:
    timeout-minutes: 10
    name: gcr.io/soluble-oss/kubectl-tap:alpine
    needs: build
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Build binary and push to GCR
      uses: docker/build-push-action@v1
      with:
        path: .
        dockerfile: Dockerfile.alpine
        username: _json_key
        password: ${{ secrets.SOLUBLE_GCR_OSS_JSON }}
        registry: gcr.io
        repository: soluble-oss/kubectl-tap
        tags: alpine

  release:
    timeout-minutes: 15
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, docker-build-scratch, docker-build-alpine]
    name: Release kubectl-tap
    runs-on: ubuntu-latest
    steps:
    - 
      name: Setup Go env
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.2'
    - 
      name: Install zsh
      run: sudo apt-get update; sudo apt-get install zsh
    - 
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - 
      name: Fetch for goreleaser
      run: git fetch --prune
    - 
      name: Build
      run: |
        go install -v -trimpath -ldflags="-s -w" ./cmd/kubectl-tap
    - 
      name: Release
      uses: goreleaser/goreleaser-action@v1.5.0
      with:
        version: v0.141.0
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.SOLUBLE_KUBETAP_BOT_TOKEN }}
    - 
      name: Update krew plugin
      if: "!contains(github.ref, '-')" # skip RCs
      uses: rajatjindal/krew-release-bot@v0.0.38
